#!/bin/sh

uci set system.@system[0].hostname=Gavin
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit luci

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q commit luci

	uci -q set system.@imm_init[0].lang="1"
	uci -q commit system
fi

uci -q set luci.main.socket="/var/run/ubus.sock"
uci -q commit luci

#if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
#	uci -q set fstab.@global[0].anon_mount="1"
#	uci -q commit fstab

#	uci -q set system.@imm_init[0].anon_mount="1"
#	uci -q commit system
#fi
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='v21.02.7'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Gavin v21.02.7 Dragon'" >> /etc/openwrt_release

ln -sf "/sbin/ip" "/usr/bin/ip"

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

rm -rf "/tmp/luci-modulecache"
rm -f "/tmp/luci-indexcache"

exit 0
