name: Update SmartDNS Rules（GFW+AD）

on:
  schedule:
    - cron: "0 */1 * * *"   # 每小时运行一次（UTC时间）
  workflow_dispatch:       # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Build gfw.conf
        run: bash build-gfw.sh

      - name: Check and download ad rules
        id: ad-check
        run: |
          # 广告规则文件及URL
          BLACKLIST="anti-ad-for-smartdns.conf"
          WHITELIST="anti-ad-white-for-smartdns.conf"
          BLACKLIST_URL="https://anti-ad.net/anti-ad-for-smartdns.conf"
          WHITELIST_URL="https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-for-smartdns.txt"
          
          # 下载广告黑名单并检查是否更新
          wget -q -O "$BLACKLIST" "$BLACKLIST_URL"
          if ! diff -q "$BLACKLIST" <(git show HEAD:"$BLACKLIST" 2>/dev/null); then
            echo "::notice::广告黑名单有更新."
            echo "ad_changes=true" >> $GITHUB_OUTPUT
          fi
          
          # 下载广告白名单并检查是否更新
          wget -q -O "$WHITELIST" "$WHITELIST_URL"
          if ! diff -q "$WHITELIST" <(git show HEAD:"$WHITELIST" 2>/dev/null); then
            echo "::notice::广告白名单有更新."
            echo "ad_changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Check for all file changes
        id: git-check
        run: |
          # 检查 gfw.conf 是否有变化
          gfw_changes=false
          if ! diff -q <(tail -n +2 gfw.conf) <(git show HEAD:gfw.conf 2>/dev/null | tail -n +2); then
            gfw_changes=true
          fi
          
          # 从上一步获取广告规则的更新状态
          ad_changes="${{ steps.ad-check.outputs.ad_changes }}"
          
          if [ "$gfw_changes" == 'true' ] || [ "$ad_changes" == 'true' ]; then
            echo "::notice::检测到规则更新 (包括 GFW 或广告规则). 正在进行提交."
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::没有规则更新. 跳过提交."
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        id: push_step
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add gfw.conf anti-ad-for-smartdns.conf anti-ad-white-for-smartdns.conf
          git commit -m "Auto update all SmartDNS rules at $(date '+%F %T')"
          git push

      - name: Notify clients to update
        if: steps.push_step.outcome == 'success'
        run: |
          echo "Notifying OpenWrt device..."
          curl -X POST \
            -H "X-Hub-Signature: ${{ secrets.OPENWRT_WEBHOOK_SECRET }}" \
            "${{ secrets.OPENWRT_WEBHOOK_URL }}"
            
          echo "Notifying Ubuntu device..."
          curl -X POST \
            -H "X-Hook-Signature: ${{ secrets.UBUNTU_WEBHOOK_SECRET }}" \
            "${{ secrets.UBUNTU_WEBHOOK_URL }}"

      - name: Job Summary
        if: always()
        run: |
          if [[ ${{ steps.git-check.outputs.changes }} == 'true' ]]; then
            echo "✅ 本次运行完成：检测到规则更新，并已成功推送到客户端。"
          else
            echo "☑️ 本次运行完成：规则列表无变化，未执行任何推送操作。"
          fi
